[versions]
agp = "8.7.3"
annotation = "1.9.1"
annotationVersion = "1.8.2"
cardviewVersion = "1.0.0"
espressoCoreVersion = "3.6.1"
gradle = "8.7.3"
gradleVersion = "8.13.1"
kotlin = "1.9.24"
coreKtx = "1.12.0"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
appcompat = "1.7.0"
kotlintestRunnerJunit5 = "3.4.2"
material = "1.12.0"
constraintlayout = "2.2.0"
lifecycleLivedataKtx = "2.8.7"
lifecycleViewmodelKtx = "2.8.7"
mockk = "1.12.2"
mockkVersion = "1.13.13"
navigationFragmentKtx = "2.8.4"
navigationUiKtx = "2.8.4"
recyclerviewVersion = "1.4.0"
roomCompiler = "2.6.1"
runner = "1.6.2"
runnerVersion = "1.5.2"
annotationJvm = "1.9.1"

[libraries]
androidx-annotation = { module = "androidx.annotation:annotation", version.ref = "annotation" }
androidx-annotation-v182 = { module = "androidx.annotation:annotation", version.ref = "annotationVersion" }
androidx-cardview = { module = "androidx.cardview:cardview", version.ref = "cardviewVersion" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-espresso-core-v361 = { module = "androidx.test.espresso:espresso-core", version.ref = "espressoCoreVersion" }
androidx-recyclerview = { module = "androidx.recyclerview:recyclerview", version.ref = "recyclerviewVersion" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "roomCompiler" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "roomCompiler" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "roomCompiler" }
androidx-runner = { module = "androidx.test:runner", version.ref = "runner" }
androidx-runner-v152 = { module = "androidx.test:runner", version.ref = "runnerVersion" }
gradle = { module = "com.android.tools.build:gradle", version.ref = "gradle" }
gradle-v822 = { module = "com.android.tools.build:gradle", version.ref = "gradleVersion" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version = "1.2.1" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version = "3.6.1" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
kotlintest-runner-junit5 = { module = "io.kotlintest:kotlintest-runner-junit5", version.ref = "kotlintestRunnerJunit5" }
material = { group = "com.google.android.material", name = "material", version = "1.12.0" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version = "2.2.0" }
androidx-lifecycle-livedata-ktx = { group = "androidx.lifecycle", name = "lifecycle-livedata-ktx", version.ref = "lifecycleLivedataKtx" }
androidx-lifecycle-viewmodel-ktx = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "lifecycleViewmodelKtx" }
androidx-navigation-fragment-ktx = { group = "androidx.navigation", name = "navigation-fragment-ktx", version.ref = "navigationFragmentKtx" }
androidx-navigation-ui-ktx = { group = "androidx.navigation", name = "navigation-ui-ktx", version.ref = "navigationUiKtx" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
mockk-v11313 = { module = "io.mockk:mockk", version.ref = "mockkVersion" }
androidx-annotation-jvm = { group = "androidx.annotation", name = "annotation-jvm", version.ref = "annotationJvm" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
android-library = { id = "com.android.library", version.ref = "agp" }

